#!/usr/bin/env sh
. "$(dirname "$0")/_/h"
echo "HOOK RUN: commit-msg" >> .husky/hook.log
echo "ARGS: $@" >> .husky/hook.log
./node_modules/.bin/commitlint --edit "$1" >> .husky/hook.log 2>&1
echo "EXIT:$?" >> .husky/hook.log
if [ $? -ne 0 ]; then
	exit 1
fi
